// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: acs2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Standards.ACS2 {

  /// <summary>Holder for reflection information generated from acs2.proto</summary>
  public static partial class Acs2Reflection {

    #region Descriptor
    /// <summary>File descriptor for acs2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Acs2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgphY3MyLnByb3RvEgRhY3MyGg9hZWxmL2NvcmUucHJvdG8aEmFlbGYvb3B0",
            "aW9ucy5wcm90byKBAQoMUmVzb3VyY2VJbmZvEioKC3dyaXRlX3BhdGhzGAEg",
            "AygLMhUuYWVsZi5TY29wZWRTdGF0ZVBhdGgSKQoKcmVhZF9wYXRocxgCIAMo",
            "CzIVLmFlbGYuU2NvcGVkU3RhdGVQYXRoEhoKEm5vbl9wYXJhbGxlbGl6YWJs",
            "ZRgDIAEoCDJLCghBQ1MyQmFzZRI/Cg9HZXRSZXNvdXJjZUluZm8SES5hZWxm",
            "LlRyYW5zYWN0aW9uGhIuYWNzMi5SZXNvdXJjZUluZm8iBYiJ9wEBQh+qAhNB",
            "RWxmLlN0YW5kYXJkcy5BQ1MyipL0AQRhY3MyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Types.CoreReflection.Descriptor, global::AElf.OptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Standards.ACS2.ResourceInfo), global::AElf.Standards.ACS2.ResourceInfo.Parser, new[]{ "WritePaths", "ReadPaths", "NonParallelizable" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ResourceInfo : pb::IMessage<ResourceInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceInfo> _parser = new pb::MessageParser<ResourceInfo>(() => new ResourceInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResourceInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Standards.ACS2.Acs2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceInfo(ResourceInfo other) : this() {
      writePaths_ = other.writePaths_.Clone();
      readPaths_ = other.readPaths_.Clone();
      nonParallelizable_ = other.nonParallelizable_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceInfo Clone() {
      return new ResourceInfo(this);
    }

    /// <summary>Field number for the "write_paths" field.</summary>
    public const int WritePathsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::AElf.Types.ScopedStatePath> _repeated_writePaths_codec
        = pb::FieldCodec.ForMessage(10, global::AElf.Types.ScopedStatePath.Parser);
    private readonly pbc::RepeatedField<global::AElf.Types.ScopedStatePath> writePaths_ = new pbc::RepeatedField<global::AElf.Types.ScopedStatePath>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AElf.Types.ScopedStatePath> WritePaths {
      get { return writePaths_; }
    }

    /// <summary>Field number for the "read_paths" field.</summary>
    public const int ReadPathsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::AElf.Types.ScopedStatePath> _repeated_readPaths_codec
        = pb::FieldCodec.ForMessage(18, global::AElf.Types.ScopedStatePath.Parser);
    private readonly pbc::RepeatedField<global::AElf.Types.ScopedStatePath> readPaths_ = new pbc::RepeatedField<global::AElf.Types.ScopedStatePath>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AElf.Types.ScopedStatePath> ReadPaths {
      get { return readPaths_; }
    }

    /// <summary>Field number for the "non_parallelizable" field.</summary>
    public const int NonParallelizableFieldNumber = 3;
    private bool nonParallelizable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NonParallelizable {
      get { return nonParallelizable_; }
      set {
        nonParallelizable_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResourceInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResourceInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!writePaths_.Equals(other.writePaths_)) return false;
      if(!readPaths_.Equals(other.readPaths_)) return false;
      if (NonParallelizable != other.NonParallelizable) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= writePaths_.GetHashCode();
      hash ^= readPaths_.GetHashCode();
      if (NonParallelizable != false) hash ^= NonParallelizable.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      writePaths_.WriteTo(output, _repeated_writePaths_codec);
      readPaths_.WriteTo(output, _repeated_readPaths_codec);
      if (NonParallelizable != false) {
        output.WriteRawTag(24);
        output.WriteBool(NonParallelizable);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      writePaths_.WriteTo(ref output, _repeated_writePaths_codec);
      readPaths_.WriteTo(ref output, _repeated_readPaths_codec);
      if (NonParallelizable != false) {
        output.WriteRawTag(24);
        output.WriteBool(NonParallelizable);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += writePaths_.CalculateSize(_repeated_writePaths_codec);
      size += readPaths_.CalculateSize(_repeated_readPaths_codec);
      if (NonParallelizable != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResourceInfo other) {
      if (other == null) {
        return;
      }
      writePaths_.Add(other.writePaths_);
      readPaths_.Add(other.readPaths_);
      if (other.NonParallelizable != false) {
        NonParallelizable = other.NonParallelizable;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            writePaths_.AddEntriesFrom(input, _repeated_writePaths_codec);
            break;
          }
          case 18: {
            readPaths_.AddEntriesFrom(input, _repeated_readPaths_codec);
            break;
          }
          case 24: {
            NonParallelizable = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            writePaths_.AddEntriesFrom(ref input, _repeated_writePaths_codec);
            break;
          }
          case 18: {
            readPaths_.AddEntriesFrom(ref input, _repeated_readPaths_codec);
            break;
          }
          case 24: {
            NonParallelizable = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
