filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/Logs/*.log
    processors:
      - add_kubernetes_metadata:
          in_cluster: true
          matchers:
            - logs_path:
                logs_path: "/app/Logs/"

setup.template.settings:
  index.number_of_shards: 5
  index.number_of_replicas: 1

setup.template.enabled: true
setup.template.overwrite: true
setup.template.name: "aefinder-app-[AppId]-[ClientType]-log-index"
setup.template.pattern: "aefinder-app-[AppId]-[ClientType]-log-index-*"

setup.ilm.enabled: false

output.elasticsearch:
  hosts: [
          "http://localhost:9200"]
  index: "aefinder-app-[AppId]-[ClientType]-log-index-%{+yyyy-MM}"
  # username: "your_username"
  # password: "your_password"
  
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~

#setup.ilm.enabled: auto
#setup.ilm.rollover_alias: "aefinder-app-[AppId]--[ClientType]-log-index"
#setup.ilm.pattern: "{now/d}-000001"
#setup.ilm.overwrite: false