filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/Logs/*.log
    fields:
      environment: "localTest"
    fields_under_root: true
    processors:
      - add_kubernetes_metadata:
          in_cluster: true
          matchers:
            - logs_path:
                logs_path: "/app/Logs/"
      - decode_json_fields:
          fields: [ "message" ]
          target: "app_log"
          overwrite_keys: true
          add_error_key: true


setup.template.settings:
  index.number_of_shards: 5
  index.number_of_replicas: 1

setup.template.enabled: true
setup.template.overwrite: true
setup.template.name: "[NameSpace]-[AppId]-log-index"
setup.template.pattern: "[NameSpace]-[AppId]-log-index-*"

setup.ilm.enabled: false

output.elasticsearch:
  hosts: [
          "http://localhost:9200"]
  index: "[NameSpace]-[AppId]-log-index-%{+yyyy-MM-dd}"
  # username: "your_username"
  # password: "your_password"
  
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
